#+title: Live in Emacs

I have always been fascinated by the text-based user interface (TUI). In the past, I tried to do everything in the terminal. I used [[https://github.com/cmus/cmus][cmus]] to play music, [[https://github.com/laurent22/joplin][joplin]] to take notes, and [[https://github.com/vim/vim][vim]] to write code. However, I found the terminal too restrictive and frustrating for my needs.

[[https://www.gnu.org/software/emacs/][Emacs]] was a name that I had heard of for a long time, but never tried. In May 2022, I decided to give it a shot, and I was astonished by its customizability and versatility. I quickly became hooked on it.

Emacs is not just an editor, but an operating system in disguise. It gives me the freedom and flexibility to do whatever I want. I enjoy living in Emacs. I use org-mode for note taking, dired for file management, [[https://github.com/kljohann/mpv.el][mpv.el]] for music playing, [[https://github.com/NicolasPetton/pass][pass.el]] for password management, and [[https://github.com/zevlg/telega.el][telega.el]] for chatting. I also tried org-agenda for scheduling, but I found it too cumbersome and complex for my liking. I eventually chose bullet journal as my preferred way of planning.

I started with using org files to generate configuration files, but I soon realized that it was hard to maintain as the configuration files grew more complex. I then switched to using [[https://github.com/purcell/emacs.d][purcell/emacs.d]] as a reference for organizing my configuration. [[https://github.com/purcell/emacs.d][purcell/emacs.d]] is an excellent configuration that I recommend to all beginners who want to build their own. To improve my configuration, I searched for a lot of information from various sources, such as [[https://www.reddit.com/r/emacs/][reddit]] and [[https://emacs-china.org/][Emacs-China]]. They are both great platforms where you can learn a lot. I also borrowed many ideas from other configurations, such as [[https://github.com/purcell/emacs.d][purcell/emacs.d]] and [[https://github.com/doomemacs/doomemacs][doomemacs/doomemacs]].

Nowadays, there are many text editors to choose from, such as vim, vscode, and sublime. But none of them can match Emacs in terms of the freedom it offers. This freedom is not only about being open source, but also about being able to build your own tools. I am grateful to Richard Stallman and everyone who contributed to making Emacs better, as well as everyone who shared their configurations.
